### PR TITLE
NVSHAS-9488: Remove Admission Control/Sigstore Verifier-related cli commands.

### PR DESCRIPTION
**Pull request by NickChungSUSE**

### CODE REVIEW

**Comment by williamlin-suse** [comment]
"Remove Admission Control/Sigstore Verifier-related cli commands" means 
1. Remove Admission Control-related cli commands"
2. Remove Sigstore-related cli commands

**Comment by NickChungSUSE** [comment]
> "Remove Admission Control/Sigstore Verifier-related cli commands" means
> 
> 1. Remove Admission Control-related cli commands"
> 2. Remove Sigstore-related cli commands

To make sure which parts of cli should be removed: 
1. All admission control and related parts, including assessment operation, policy, and system information.
2. All Sigstore control and related parts, including registry.

**Comment by williamlin-suse** [comment]
> Hi @williamlin-suse, Could you please help to check if the list for removing cli is right? Thanks!
> 
> > "Remove Admission Control/Sigstore Verifier-related cli commands" means
> > 
> > 1. Remove Admission Control-related cli commands"
> > 2. Remove Sigstore-related cli commands
> 
> To make sure which parts of cli should be removed:
> 
>     1. All admission control and related parts, including assessment operation, policy, and system information.
> 
>     2. All Sigstore control and related parts, including registry.

Correct. Thanks

**Review by williamlin-suse — APPROVED** [review]
LGTM

**Review by BinX-Suse — APPROVED** [review]

**Review by jeffhuang4704 — COMMENTED** [review]
LGTM

**Comment by BinX-Suse** [comment]
Hold it for now, we will merge it after 5.4.1

**Pull request closed without merging**
