### PR TITLE
NVSHAS-9702: NeuVector Manager Pod Error / NeuVector Web UI Unavailable

### PR DESCRIPTION
**Pull request by NickChungSUSE**
FIPS setup

change config file path

add required dependencies for FIPS

change supporting algorithm

### CODE REVIEW

**Review by BinX-Suse — APPROVED** [review]
LGTM.

**Comment by xingzhang-suse** [comment]
Close this case until NeuVector officially support FIPS in whole product.

**Comment by Sbennett99** [comment]
is there an eta this ?

**Comment by BinX-Suse** [comment]
@Sbennett99 Full FIPS support is scheduled for the 6.0 release, though the exact release date has not yet been determined.

**Pull request closed without merging**
